services:
  - type: web
    name: weathersense-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: sh start.sh
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENWEATHER_API_KEY
        value: db41ab449fa4a5a7ad97e93b644e9cf2
      - key: ADMIN_KEY
        value: weathersense_admin_secret
